# destination_db: public
# destination_schema: example_model

description:
  model: unified and enriched data from multiple marketing sources
  tables:
    example_1: all channels daily aggregation view for marketing metrics
    example_2: all channels monthly aggregation view for marketing metrics
